// Code generated by xgen. DO NOT EDIT.

package schema_offers

import (
	"encoding/xml"
)

type КоммерческаяИнформация struct {
	XMLName                    xml.Name `xml:"КоммерческаяИнформация"`
	Text                       string   `xml:",chardata"`
	Xmlns                      string   `xml:"xmlns,attr"`
	Xs                         string   `xml:"xs,attr"`
	Xsi                        string   `xml:"xsi,attr"`
	ВерсияСхемы                string   `xml:"ВерсияСхемы,attr"`
	ДатаФормирования           string   `xml:"ДатаФормирования,attr"`
	ИзмененияПакетаПредложений struct {
		Text        string `xml:",chardata"`
		Ид          string `xml:"Ид"`
		ИдКаталога  string `xml:"ИдКаталога"`
		Предложения struct {
			Text        string `xml:",chardata"`
			Предложение []struct {
				Text   string `xml:",chardata"`
				Ид     string `xml:"Ид"`
				Склады []struct {
					Text               string `xml:",chardata"`
					ИдСклада           string `xml:"ИдСклада,attr"`
					КоличествоНаСкладе string `xml:"КоличествоНаСкладе,attr"`
				} `xml:"Склады"`
				Количество       string `xml:"Количество"`
				ИдХарактеристики string `xml:"ИдХарактеристики"`
			} `xml:"Предложение"`
		} `xml:"Предложения"`
	} `xml:"ИзмененияПакетаПредложений"`
} 
